// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0DPuIFVIcLQRA8sqtuxaoGFvrB6TUpLc',
    appId: '1:800726372250:web:076b8fea015875ebb4b423',
    messagingSenderId: '800726372250',
    projectId: 'caco-d7372',
    authDomain: 'caco-d7372.firebaseapp.com',
    storageBucket: 'caco-d7372.firebasestorage.app',
    measurementId: 'G-8N7HE7WW6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAKADBmXwSSXkp8kh5qBeVN9TQVMEFFBc',
    appId: '1:800726372250:android:226bbb5cd3037c63b4b423',
    messagingSenderId: '800726372250',
    projectId: 'caco-d7372',
    storageBucket: 'caco-d7372.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVKBpFpVxj6v-kRZY20_DbxcyuvFQisC4',
    appId: '1:800726372250:ios:a523a45a1e6bcbaab4b423',
    messagingSenderId: '800726372250',
    projectId: 'caco-d7372',
    storageBucket: 'caco-d7372.firebasestorage.app',
    iosBundleId: 'com.example.cc',
  );
}
